# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Tigrinya spellchecker"
ti = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Tigrinya, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
ti = "TRANSLATE: A spellchecker for Tigrinya, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.ti"

[windows]
system_product_code = "{81C624DA-DA1C-4336-B20B-8F38E1BCBD7E}_is1"
legacy_product_codes = [
    { value = "110999CA-5C5F-491E-A8AC-9D4331606B66", kind = "nsis" },
    { value = "98CC400E-6960-4B34-92F5-DC5127B23AB4", kind = "nsis" }
]

[package.speller]
name = "Tigrinya"
version = "0.1.1"

[package.grammar]
name = "Tigrinya"
version = "0.1.0"

[package.tts-text-proc]
name = "Tigrinya"
version = "0.1.0"
