template = "https://github.com/giellalt/template-lang-und"
rev_id = 266
template_sha = "0bf1857d37e3d9d859c2f97c9772ed27d291955c"

[replacements]
__GLOTTOLOG_ID__ = "tigr1271"
__REPO__ = "lang-tir"
__UND2C__ = "ti"
__UNDEFINED__ = "Tigrinya"
__UND__ = "tir"
