template = "https://github.com/giellalt/template-lang-und"
rev_id = 274
template_sha = "43a0f0c0afaa856365e2bf3d3cb7eae06d27cc4d"

[replacements]
__GLOTTOLOG_ID__ = "tigr1271"
__REPO__ = "lang-tir"
__UND2C__ = "ti"
__UNDEFINED__ = "Tigrinya"
__UND__ = "tir"
